name: Automatic Deployment
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Notify Update Service
      run: curl -X GET "https://deploy.kessaft.tk/deploy?name=schudu&path=schudu/web&secret=${{secrets.AUTH_TOKEN}}"
