name: Automatic Deployment
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Print Secret for validation
      env: 
        SECRET: ${{ secrets.SECRET_TOKEN }}
      run: echo "${{secrets.AUTH_TOKEN}}"; echo "$SECRET"; echo "https://kessaft.tk/ci/deploy?name=schudu&path=schudu/web&secret=${{secrets.AUTH_TOKEN}}"; echo "https://kessaft.tk/ci/deploy?name=schudu&path=schudu/web&secret=$SECRET}"
    - name: Notify Update Service
      run: curl -X GET "https://kessaft.tk/ci/deploy?name=schudu&path=schudu/web&secret=${{secrets.AUTH_TOKEN}}"
